/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CostCheckRouteImport } from './routes/cost-check'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DrawerRouteImport } from './routes/drawer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PaymentsGuideRouteImport } from './routes/payments-guide'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StockTakeRouteImport } from './routes/stock-take'
import { Route as SupplierPaymentRouteImport } from './routes/supplier-payment'
import { Route as UatRouteImport } from './routes/uat'
import { Route as WastageRouteImport } from './routes/wastage'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'
import { Route as ApiPublicBusinessSignupRouteImport } from './routes/api/public/business-signup'
import { Route as ApiPublicCashDrawerCloseRouteImport } from './routes/api/public/cash-drawer-close'
import { Route as ApiPublicCashDrawerForceCloseRouteImport } from './routes/api/public/cash-drawer-force-close'
import { Route as ApiPublicCateringRemindersRouteImport } from './routes/api/public/catering-reminders'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicDailySummaryRouteImport } from './routes/api/public/daily-summary'
import { Route as ApiPublicExpiryRemindersRouteImport } from './routes/api/public/expiry-reminders'
import { Route as ApiPublicNewsWatchRouteImport } from './routes/api/public/news-watch'
import { Route as ApiPublicPaymentConnectRouteImport } from './routes/api/public/payment-connect'
import { Route as ApiPublicPaymentStartRouteImport } from './routes/api/public/payment-start'
import { Route as ApiPublicPaymentTestRouteImport } from './routes/api/public/payment-test'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'
import { Route as ApiPublicPingRouteImport } from './routes/api/public/ping'
import { Route as ApiPublicPlatformAdminRouteImport } from './routes/api/public/platform-admin'
import { Route as ApiPublicStaffAdminRouteImport } from './routes/api/public/staff-admin'
import { Route as ApiPublicStaffPinLoginRouteImport } from './routes/api/public/staff-pin-login'
import { Route as ApiPublicSummaryUnsubscribeRouteImport } from './routes/api/public/summary-unsubscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CostCheckRoute = CostCheckRouteImport.update({
  id: '/cost-check',
  path: '/cost-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawerRoute = DrawerRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsGuideRoute = PaymentsGuideRouteImport.update({
  id: '/payments-guide',
  path: '/payments-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTakeRoute = StockTakeRouteImport.update({
  id: '/stock-take',
  path: '/stock-take',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPaymentRoute = SupplierPaymentRouteImport.update({
  id: '/supplier-payment',
  path: '/supplier-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const UatRoute = UatRouteImport.update({
  id: '/uat',
  path: '/uat',
  getParentRoute: () => rootRouteImport,
} as any)
const WastageRoute = WastageRouteImport.update({
  id: '/wastage',
  path: '/wastage',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBusinessSignupRoute = ApiPublicBusinessSignupRouteImport.update({
  id: '/api/public/business-signup',
  path: '/api/public/business-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashDrawerCloseRoute =
  ApiPublicCashDrawerCloseRouteImport.update({
    id: '/api/public/cash-drawer-close',
    path: '/api/public/cash-drawer-close',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCashDrawerForceCloseRoute =
  ApiPublicCashDrawerForceCloseRouteImport.update({
    id: '/api/public/cash-drawer-force-close',
    path: '/api/public/cash-drawer-force-close',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCateringRemindersRoute =
  ApiPublicCateringRemindersRouteImport.update({
    id: '/api/public/catering-reminders',
    path: '/api/public/catering-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailySummaryRoute = ApiPublicDailySummaryRouteImport.update({
  id: '/api/public/daily-summary',
  path: '/api/public/daily-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpiryRemindersRoute =
  ApiPublicExpiryRemindersRouteImport.update({
    id: '/api/public/expiry-reminders',
    path: '/api/public/expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsWatchRoute = ApiPublicNewsWatchRouteImport.update({
  id: '/api/public/news-watch',
  path: '/api/public/news-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentConnectRoute = ApiPublicPaymentConnectRouteImport.update({
  id: '/api/public/payment-connect',
  path: '/api/public/payment-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentStartRoute = ApiPublicPaymentStartRouteImport.update({
  id: '/api/public/payment-start',
  path: '/api/public/payment-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentTestRoute = ApiPublicPaymentTestRouteImport.update({
  id: '/api/public/payment-test',
  path: '/api/public/payment-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPingRoute = ApiPublicPingRouteImport.update({
  id: '/api/public/ping',
  path: '/api/public/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlatformAdminRoute = ApiPublicPlatformAdminRouteImport.update({
  id: '/api/public/platform-admin',
  path: '/api/public/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaffAdminRoute = ApiPublicStaffAdminRouteImport.update({
  id: '/api/public/staff-admin',
  path: '/api/public/staff-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaffPinLoginRoute = ApiPublicStaffPinLoginRouteImport.update({
  id: '/api/public/staff-pin-login',
  path: '/api/public/staff-pin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSummaryUnsubscribeRoute =
  ApiPublicSummaryUnsubscribeRouteImport.update({
    id: '/api/public/summary-unsubscribe',
    path: '/api/public/summary-unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/batches': typeof BatchesRoute
  '/cashflow': typeof CashflowRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/cost-check': typeof CostCheckRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/drawer': typeof DrawerRoute
  '/faq': typeof FaqRoute
  '/flags': typeof FlagsRoute
  '/ingredients': typeof IngredientsRoute
  '/orders': typeof OrdersRoute
  '/our-story': typeof OurStoryRoute
  '/payments': typeof PaymentsRoute
  '/payments-guide': typeof PaymentsGuideRoute
  '/payouts': typeof PayoutsRoute
  '/pos': typeof PosRoute
  '/presentation': typeof PresentationRoute
  '/purchases': typeof PurchasesRoute
  '/recipes': typeof RecipesRoute
  '/report': typeof ReportRoute
  '/resources': typeof ResourcesRoute
  '/shopping-list': typeof ShoppingListRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/stock-take': typeof StockTakeRoute
  '/supplier-payment': typeof SupplierPaymentRoute
  '/uat': typeof UatRoute
  '/wastage': typeof WastageRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/public/business-signup': typeof ApiPublicBusinessSignupRoute
  '/api/public/cash-drawer-close': typeof ApiPublicCashDrawerCloseRoute
  '/api/public/cash-drawer-force-close': typeof ApiPublicCashDrawerForceCloseRoute
  '/api/public/catering-reminders': typeof ApiPublicCateringRemindersRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/daily-summary': typeof ApiPublicDailySummaryRoute
  '/api/public/expiry-reminders': typeof ApiPublicExpiryRemindersRoute
  '/api/public/news-watch': typeof ApiPublicNewsWatchRoute
  '/api/public/payment-connect': typeof ApiPublicPaymentConnectRoute
  '/api/public/payment-start': typeof ApiPublicPaymentStartRoute
  '/api/public/payment-test': typeof ApiPublicPaymentTestRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/platform-admin': typeof ApiPublicPlatformAdminRoute
  '/api/public/staff-admin': typeof ApiPublicStaffAdminRoute
  '/api/public/staff-pin-login': typeof ApiPublicStaffPinLoginRoute
  '/api/public/summary-unsubscribe': typeof ApiPublicSummaryUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/batches': typeof BatchesRoute
  '/cashflow': typeof CashflowRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/cost-check': typeof CostCheckRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/drawer': typeof DrawerRoute
  '/faq': typeof FaqRoute
  '/flags': typeof FlagsRoute
  '/ingredients': typeof IngredientsRoute
  '/orders': typeof OrdersRoute
  '/our-story': typeof OurStoryRoute
  '/payments': typeof PaymentsRoute
  '/payments-guide': typeof PaymentsGuideRoute
  '/payouts': typeof PayoutsRoute
  '/pos': typeof PosRoute
  '/presentation': typeof PresentationRoute
  '/purchases': typeof PurchasesRoute
  '/recipes': typeof RecipesRoute
  '/report': typeof ReportRoute
  '/resources': typeof ResourcesRoute
  '/shopping-list': typeof ShoppingListRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/stock-take': typeof StockTakeRoute
  '/supplier-payment': typeof SupplierPaymentRoute
  '/uat': typeof UatRoute
  '/wastage': typeof WastageRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/api/public/business-signup': typeof ApiPublicBusinessSignupRoute
  '/api/public/cash-drawer-close': typeof ApiPublicCashDrawerCloseRoute
  '/api/public/cash-drawer-force-close': typeof ApiPublicCashDrawerForceCloseRoute
  '/api/public/catering-reminders': typeof ApiPublicCateringRemindersRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/daily-summary': typeof ApiPublicDailySummaryRoute
  '/api/public/expiry-reminders': typeof ApiPublicExpiryRemindersRoute
  '/api/public/news-watch': typeof ApiPublicNewsWatchRoute
  '/api/public/payment-connect': typeof ApiPublicPaymentConnectRoute
  '/api/public/payment-start': typeof ApiPublicPaymentStartRoute
  '/api/public/payment-test': typeof ApiPublicPaymentTestRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/platform-admin': typeof ApiPublicPlatformAdminRoute
  '/api/public/staff-admin': typeof ApiPublicStaffAdminRoute
  '/api/public/staff-pin-login': typeof ApiPublicStaffPinLoginRoute
  '/api/public/summary-unsubscribe': typeof ApiPublicSummaryUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/batches': typeof BatchesRoute
  '/cashflow': typeof CashflowRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/cost-check': typeof CostCheckRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/drawer': typeof DrawerRoute
  '/faq': typeof FaqRoute
  '/flags': typeof FlagsRoute
  '/ingredients': typeof IngredientsRoute
  '/orders': typeof OrdersRoute
  '/our-story': typeof OurStoryRoute
  '/payments': typeof PaymentsRoute
  '/payments-guide': typeof PaymentsGuideRoute
  '/payouts': typeof PayoutsRoute
  '/pos': typeof PosRoute
  '/presentation': typeof PresentationRoute
  '/purchases': typeof PurchasesRoute
  '/recipes': typeof RecipesRoute
  '/report': typeof ReportRoute
  '/resources': typeof ResourcesRoute
  '/shopping-list': typeof ShoppingListRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/stock-take': typeof StockTakeRoute
  '/supplier-payment': typeof SupplierPaymentRoute
  '/uat': typeof UatRoute
  '/wastage': typeof WastageRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/public/business-signup': typeof ApiPublicBusinessSignupRoute
  '/api/public/cash-drawer-close': typeof ApiPublicCashDrawerCloseRoute
  '/api/public/cash-drawer-force-close': typeof ApiPublicCashDrawerForceCloseRoute
  '/api/public/catering-reminders': typeof ApiPublicCateringRemindersRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/daily-summary': typeof ApiPublicDailySummaryRoute
  '/api/public/expiry-reminders': typeof ApiPublicExpiryRemindersRoute
  '/api/public/news-watch': typeof ApiPublicNewsWatchRoute
  '/api/public/payment-connect': typeof ApiPublicPaymentConnectRoute
  '/api/public/payment-start': typeof ApiPublicPaymentStartRoute
  '/api/public/payment-test': typeof ApiPublicPaymentTestRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/platform-admin': typeof ApiPublicPlatformAdminRoute
  '/api/public/staff-admin': typeof ApiPublicStaffAdminRoute
  '/api/public/staff-pin-login': typeof ApiPublicStaffPinLoginRoute
  '/api/public/summary-unsubscribe': typeof ApiPublicSummaryUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/approvals'
    | '/audit'
    | '/batches'
    | '/cashflow'
    | '/catering'
    | '/contact'
    | '/cost-check'
    | '/credit'
    | '/dashboard'
    | '/drawer'
    | '/faq'
    | '/flags'
    | '/ingredients'
    | '/orders'
    | '/our-story'
    | '/payments'
    | '/payments-guide'
    | '/payouts'
    | '/pos'
    | '/presentation'
    | '/purchases'
    | '/recipes'
    | '/report'
    | '/resources'
    | '/shopping-list'
    | '/signup'
    | '/staff'
    | '/stock-take'
    | '/supplier-payment'
    | '/uat'
    | '/wastage'
    | '/suppliers/$supplierId'
    | '/suppliers/'
    | '/api/public/business-signup'
    | '/api/public/cash-drawer-close'
    | '/api/public/cash-drawer-force-close'
    | '/api/public/catering-reminders'
    | '/api/public/contact'
    | '/api/public/daily-summary'
    | '/api/public/expiry-reminders'
    | '/api/public/news-watch'
    | '/api/public/payment-connect'
    | '/api/public/payment-start'
    | '/api/public/payment-test'
    | '/api/public/payment-webhook'
    | '/api/public/ping'
    | '/api/public/platform-admin'
    | '/api/public/staff-admin'
    | '/api/public/staff-pin-login'
    | '/api/public/summary-unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/approvals'
    | '/audit'
    | '/batches'
    | '/cashflow'
    | '/catering'
    | '/contact'
    | '/cost-check'
    | '/credit'
    | '/dashboard'
    | '/drawer'
    | '/faq'
    | '/flags'
    | '/ingredients'
    | '/orders'
    | '/our-story'
    | '/payments'
    | '/payments-guide'
    | '/payouts'
    | '/pos'
    | '/presentation'
    | '/purchases'
    | '/recipes'
    | '/report'
    | '/resources'
    | '/shopping-list'
    | '/signup'
    | '/staff'
    | '/stock-take'
    | '/supplier-payment'
    | '/uat'
    | '/wastage'
    | '/suppliers/$supplierId'
    | '/suppliers'
    | '/api/public/business-signup'
    | '/api/public/cash-drawer-close'
    | '/api/public/cash-drawer-force-close'
    | '/api/public/catering-reminders'
    | '/api/public/contact'
    | '/api/public/daily-summary'
    | '/api/public/expiry-reminders'
    | '/api/public/news-watch'
    | '/api/public/payment-connect'
    | '/api/public/payment-start'
    | '/api/public/payment-test'
    | '/api/public/payment-webhook'
    | '/api/public/ping'
    | '/api/public/platform-admin'
    | '/api/public/staff-admin'
    | '/api/public/staff-pin-login'
    | '/api/public/summary-unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/approvals'
    | '/audit'
    | '/batches'
    | '/cashflow'
    | '/catering'
    | '/contact'
    | '/cost-check'
    | '/credit'
    | '/dashboard'
    | '/drawer'
    | '/faq'
    | '/flags'
    | '/ingredients'
    | '/orders'
    | '/our-story'
    | '/payments'
    | '/payments-guide'
    | '/payouts'
    | '/pos'
    | '/presentation'
    | '/purchases'
    | '/recipes'
    | '/report'
    | '/resources'
    | '/shopping-list'
    | '/signup'
    | '/staff'
    | '/stock-take'
    | '/supplier-payment'
    | '/uat'
    | '/wastage'
    | '/suppliers/$supplierId'
    | '/suppliers/'
    | '/api/public/business-signup'
    | '/api/public/cash-drawer-close'
    | '/api/public/cash-drawer-force-close'
    | '/api/public/catering-reminders'
    | '/api/public/contact'
    | '/api/public/daily-summary'
    | '/api/public/expiry-reminders'
    | '/api/public/news-watch'
    | '/api/public/payment-connect'
    | '/api/public/payment-start'
    | '/api/public/payment-test'
    | '/api/public/payment-webhook'
    | '/api/public/ping'
    | '/api/public/platform-admin'
    | '/api/public/staff-admin'
    | '/api/public/staff-pin-login'
    | '/api/public/summary-unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BatchesRoute: typeof BatchesRoute
  CashflowRoute: typeof CashflowRoute
  CateringRoute: typeof CateringRoute
  ContactRoute: typeof ContactRoute
  CostCheckRoute: typeof CostCheckRoute
  CreditRoute: typeof CreditRoute
  DashboardRoute: typeof DashboardRoute
  DrawerRoute: typeof DrawerRoute
  FaqRoute: typeof FaqRoute
  FlagsRoute: typeof FlagsRoute
  IngredientsRoute: typeof IngredientsRoute
  OrdersRoute: typeof OrdersRoute
  OurStoryRoute: typeof OurStoryRoute
  PaymentsRoute: typeof PaymentsRoute
  PaymentsGuideRoute: typeof PaymentsGuideRoute
  PayoutsRoute: typeof PayoutsRoute
  PosRoute: typeof PosRoute
  PresentationRoute: typeof PresentationRoute
  PurchasesRoute: typeof PurchasesRoute
  RecipesRoute: typeof RecipesRoute
  ReportRoute: typeof ReportRoute
  ResourcesRoute: typeof ResourcesRoute
  ShoppingListRoute: typeof ShoppingListRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  StockTakeRoute: typeof StockTakeRoute
  SupplierPaymentRoute: typeof SupplierPaymentRoute
  UatRoute: typeof UatRoute
  WastageRoute: typeof WastageRoute
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  ApiPublicBusinessSignupRoute: typeof ApiPublicBusinessSignupRoute
  ApiPublicCashDrawerCloseRoute: typeof ApiPublicCashDrawerCloseRoute
  ApiPublicCashDrawerForceCloseRoute: typeof ApiPublicCashDrawerForceCloseRoute
  ApiPublicCateringRemindersRoute: typeof ApiPublicCateringRemindersRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicDailySummaryRoute: typeof ApiPublicDailySummaryRoute
  ApiPublicExpiryRemindersRoute: typeof ApiPublicExpiryRemindersRoute
  ApiPublicNewsWatchRoute: typeof ApiPublicNewsWatchRoute
  ApiPublicPaymentConnectRoute: typeof ApiPublicPaymentConnectRoute
  ApiPublicPaymentStartRoute: typeof ApiPublicPaymentStartRoute
  ApiPublicPaymentTestRoute: typeof ApiPublicPaymentTestRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
  ApiPublicPingRoute: typeof ApiPublicPingRoute
  ApiPublicPlatformAdminRoute: typeof ApiPublicPlatformAdminRoute
  ApiPublicStaffAdminRoute: typeof ApiPublicStaffAdminRoute
  ApiPublicStaffPinLoginRoute: typeof ApiPublicStaffPinLoginRoute
  ApiPublicSummaryUnsubscribeRoute: typeof ApiPublicSummaryUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-check': {
      id: '/cost-check'
      path: '/cost-check'
      fullPath: '/cost-check'
      preLoaderRoute: typeof CostCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawer': {
      id: '/drawer'
      path: '/drawer'
      fullPath: '/drawer'
      preLoaderRoute: typeof DrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments-guide': {
      id: '/payments-guide'
      path: '/payments-guide'
      fullPath: '/payments-guide'
      preLoaderRoute: typeof PaymentsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-take': {
      id: '/stock-take'
      path: '/stock-take'
      fullPath: '/stock-take'
      preLoaderRoute: typeof StockTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-payment': {
      id: '/supplier-payment'
      path: '/supplier-payment'
      fullPath: '/supplier-payment'
      preLoaderRoute: typeof SupplierPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uat': {
      id: '/uat'
      path: '/uat'
      fullPath: '/uat'
      preLoaderRoute: typeof UatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wastage': {
      id: '/wastage'
      path: '/wastage'
      fullPath: '/wastage'
      preLoaderRoute: typeof WastageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/business-signup': {
      id: '/api/public/business-signup'
      path: '/api/public/business-signup'
      fullPath: '/api/public/business-signup'
      preLoaderRoute: typeof ApiPublicBusinessSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cash-drawer-close': {
      id: '/api/public/cash-drawer-close'
      path: '/api/public/cash-drawer-close'
      fullPath: '/api/public/cash-drawer-close'
      preLoaderRoute: typeof ApiPublicCashDrawerCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cash-drawer-force-close': {
      id: '/api/public/cash-drawer-force-close'
      path: '/api/public/cash-drawer-force-close'
      fullPath: '/api/public/cash-drawer-force-close'
      preLoaderRoute: typeof ApiPublicCashDrawerForceCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catering-reminders': {
      id: '/api/public/catering-reminders'
      path: '/api/public/catering-reminders'
      fullPath: '/api/public/catering-reminders'
      preLoaderRoute: typeof ApiPublicCateringRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-summary': {
      id: '/api/public/daily-summary'
      path: '/api/public/daily-summary'
      fullPath: '/api/public/daily-summary'
      preLoaderRoute: typeof ApiPublicDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expiry-reminders': {
      id: '/api/public/expiry-reminders'
      path: '/api/public/expiry-reminders'
      fullPath: '/api/public/expiry-reminders'
      preLoaderRoute: typeof ApiPublicExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news-watch': {
      id: '/api/public/news-watch'
      path: '/api/public/news-watch'
      fullPath: '/api/public/news-watch'
      preLoaderRoute: typeof ApiPublicNewsWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-connect': {
      id: '/api/public/payment-connect'
      path: '/api/public/payment-connect'
      fullPath: '/api/public/payment-connect'
      preLoaderRoute: typeof ApiPublicPaymentConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-start': {
      id: '/api/public/payment-start'
      path: '/api/public/payment-start'
      fullPath: '/api/public/payment-start'
      preLoaderRoute: typeof ApiPublicPaymentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-test': {
      id: '/api/public/payment-test'
      path: '/api/public/payment-test'
      fullPath: '/api/public/payment-test'
      preLoaderRoute: typeof ApiPublicPaymentTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ping': {
      id: '/api/public/ping'
      path: '/api/public/ping'
      fullPath: '/api/public/ping'
      preLoaderRoute: typeof ApiPublicPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/platform-admin': {
      id: '/api/public/platform-admin'
      path: '/api/public/platform-admin'
      fullPath: '/api/public/platform-admin'
      preLoaderRoute: typeof ApiPublicPlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-admin': {
      id: '/api/public/staff-admin'
      path: '/api/public/staff-admin'
      fullPath: '/api/public/staff-admin'
      preLoaderRoute: typeof ApiPublicStaffAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-pin-login': {
      id: '/api/public/staff-pin-login'
      path: '/api/public/staff-pin-login'
      fullPath: '/api/public/staff-pin-login'
      preLoaderRoute: typeof ApiPublicStaffPinLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/summary-unsubscribe': {
      id: '/api/public/summary-unsubscribe'
      path: '/api/public/summary-unsubscribe'
      fullPath: '/api/public/summary-unsubscribe'
      preLoaderRoute: typeof ApiPublicSummaryUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BatchesRoute: BatchesRoute,
  CashflowRoute: CashflowRoute,
  CateringRoute: CateringRoute,
  ContactRoute: ContactRoute,
  CostCheckRoute: CostCheckRoute,
  CreditRoute: CreditRoute,
  DashboardRoute: DashboardRoute,
  DrawerRoute: DrawerRoute,
  FaqRoute: FaqRoute,
  FlagsRoute: FlagsRoute,
  IngredientsRoute: IngredientsRoute,
  OrdersRoute: OrdersRoute,
  OurStoryRoute: OurStoryRoute,
  PaymentsRoute: PaymentsRoute,
  PaymentsGuideRoute: PaymentsGuideRoute,
  PayoutsRoute: PayoutsRoute,
  PosRoute: PosRoute,
  PresentationRoute: PresentationRoute,
  PurchasesRoute: PurchasesRoute,
  RecipesRoute: RecipesRoute,
  ReportRoute: ReportRoute,
  ResourcesRoute: ResourcesRoute,
  ShoppingListRoute: ShoppingListRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  StockTakeRoute: StockTakeRoute,
  SupplierPaymentRoute: SupplierPaymentRoute,
  UatRoute: UatRoute,
  WastageRoute: WastageRoute,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  ApiPublicBusinessSignupRoute: ApiPublicBusinessSignupRoute,
  ApiPublicCashDrawerCloseRoute: ApiPublicCashDrawerCloseRoute,
  ApiPublicCashDrawerForceCloseRoute: ApiPublicCashDrawerForceCloseRoute,
  ApiPublicCateringRemindersRoute: ApiPublicCateringRemindersRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicDailySummaryRoute: ApiPublicDailySummaryRoute,
  ApiPublicExpiryRemindersRoute: ApiPublicExpiryRemindersRoute,
  ApiPublicNewsWatchRoute: ApiPublicNewsWatchRoute,
  ApiPublicPaymentConnectRoute: ApiPublicPaymentConnectRoute,
  ApiPublicPaymentStartRoute: ApiPublicPaymentStartRoute,
  ApiPublicPaymentTestRoute: ApiPublicPaymentTestRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
  ApiPublicPingRoute: ApiPublicPingRoute,
  ApiPublicPlatformAdminRoute: ApiPublicPlatformAdminRoute,
  ApiPublicStaffAdminRoute: ApiPublicStaffAdminRoute,
  ApiPublicStaffPinLoginRoute: ApiPublicStaffPinLoginRoute,
  ApiPublicSummaryUnsubscribeRoute: ApiPublicSummaryUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
