/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DrawerRouteImport } from './routes/drawer'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SupplierPaymentRouteImport } from './routes/supplier-payment'
import { Route as WastageRouteImport } from './routes/wastage'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'
import { Route as ApiPublicCashDrawerCloseRouteImport } from './routes/api/public/cash-drawer-close'
import { Route as ApiPublicStaffAdminRouteImport } from './routes/api/public/staff-admin'
import { Route as ApiPublicStaffPinLoginRouteImport } from './routes/api/public/staff-pin-login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawerRoute = DrawerRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPaymentRoute = SupplierPaymentRouteImport.update({
  id: '/supplier-payment',
  path: '/supplier-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const WastageRoute = WastageRouteImport.update({
  id: '/wastage',
  path: '/wastage',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashDrawerCloseRoute =
  ApiPublicCashDrawerCloseRouteImport.update({
    id: '/api/public/cash-drawer-close',
    path: '/api/public/cash-drawer-close',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStaffAdminRoute = ApiPublicStaffAdminRouteImport.update({
  id: '/api/public/staff-admin',
  path: '/api/public/staff-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaffPinLoginRoute = ApiPublicStaffPinLoginRouteImport.update({
  id: '/api/public/staff-pin-login',
  path: '/api/public/staff-pin-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/catering': typeof CateringRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/drawer': typeof DrawerRoute
  '/flags': typeof FlagsRoute
  '/ingredients': typeof IngredientsRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/recipes': typeof RecipesRoute
  '/staff': typeof StaffRoute
  '/supplier-payment': typeof SupplierPaymentRoute
  '/wastage': typeof WastageRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/public/cash-drawer-close': typeof ApiPublicCashDrawerCloseRoute
  '/api/public/staff-admin': typeof ApiPublicStaffAdminRoute
  '/api/public/staff-pin-login': typeof ApiPublicStaffPinLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/catering': typeof CateringRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/drawer': typeof DrawerRoute
  '/flags': typeof FlagsRoute
  '/ingredients': typeof IngredientsRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/recipes': typeof RecipesRoute
  '/staff': typeof StaffRoute
  '/supplier-payment': typeof SupplierPaymentRoute
  '/wastage': typeof WastageRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/api/public/cash-drawer-close': typeof ApiPublicCashDrawerCloseRoute
  '/api/public/staff-admin': typeof ApiPublicStaffAdminRoute
  '/api/public/staff-pin-login': typeof ApiPublicStaffPinLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/catering': typeof CateringRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/drawer': typeof DrawerRoute
  '/flags': typeof FlagsRoute
  '/ingredients': typeof IngredientsRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/recipes': typeof RecipesRoute
  '/staff': typeof StaffRoute
  '/supplier-payment': typeof SupplierPaymentRoute
  '/wastage': typeof WastageRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/public/cash-drawer-close': typeof ApiPublicCashDrawerCloseRoute
  '/api/public/staff-admin': typeof ApiPublicStaffAdminRoute
  '/api/public/staff-pin-login': typeof ApiPublicStaffPinLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/catering'
    | '/credit'
    | '/dashboard'
    | '/drawer'
    | '/flags'
    | '/ingredients'
    | '/pos'
    | '/purchases'
    | '/recipes'
    | '/staff'
    | '/supplier-payment'
    | '/wastage'
    | '/suppliers/$supplierId'
    | '/suppliers/'
    | '/api/public/cash-drawer-close'
    | '/api/public/staff-admin'
    | '/api/public/staff-pin-login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/catering'
    | '/credit'
    | '/dashboard'
    | '/drawer'
    | '/flags'
    | '/ingredients'
    | '/pos'
    | '/purchases'
    | '/recipes'
    | '/staff'
    | '/supplier-payment'
    | '/wastage'
    | '/suppliers/$supplierId'
    | '/suppliers'
    | '/api/public/cash-drawer-close'
    | '/api/public/staff-admin'
    | '/api/public/staff-pin-login'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/catering'
    | '/credit'
    | '/dashboard'
    | '/drawer'
    | '/flags'
    | '/ingredients'
    | '/pos'
    | '/purchases'
    | '/recipes'
    | '/staff'
    | '/supplier-payment'
    | '/wastage'
    | '/suppliers/$supplierId'
    | '/suppliers/'
    | '/api/public/cash-drawer-close'
    | '/api/public/staff-admin'
    | '/api/public/staff-pin-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  CateringRoute: typeof CateringRoute
  CreditRoute: typeof CreditRoute
  DashboardRoute: typeof DashboardRoute
  DrawerRoute: typeof DrawerRoute
  FlagsRoute: typeof FlagsRoute
  IngredientsRoute: typeof IngredientsRoute
  PosRoute: typeof PosRoute
  PurchasesRoute: typeof PurchasesRoute
  RecipesRoute: typeof RecipesRoute
  StaffRoute: typeof StaffRoute
  SupplierPaymentRoute: typeof SupplierPaymentRoute
  WastageRoute: typeof WastageRoute
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  ApiPublicCashDrawerCloseRoute: typeof ApiPublicCashDrawerCloseRoute
  ApiPublicStaffAdminRoute: typeof ApiPublicStaffAdminRoute
  ApiPublicStaffPinLoginRoute: typeof ApiPublicStaffPinLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawer': {
      id: '/drawer'
      path: '/drawer'
      fullPath: '/drawer'
      preLoaderRoute: typeof DrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-payment': {
      id: '/supplier-payment'
      path: '/supplier-payment'
      fullPath: '/supplier-payment'
      preLoaderRoute: typeof SupplierPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wastage': {
      id: '/wastage'
      path: '/wastage'
      fullPath: '/wastage'
      preLoaderRoute: typeof WastageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cash-drawer-close': {
      id: '/api/public/cash-drawer-close'
      path: '/api/public/cash-drawer-close'
      fullPath: '/api/public/cash-drawer-close'
      preLoaderRoute: typeof ApiPublicCashDrawerCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-admin': {
      id: '/api/public/staff-admin'
      path: '/api/public/staff-admin'
      fullPath: '/api/public/staff-admin'
      preLoaderRoute: typeof ApiPublicStaffAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-pin-login': {
      id: '/api/public/staff-pin-login'
      path: '/api/public/staff-pin-login'
      fullPath: '/api/public/staff-pin-login'
      preLoaderRoute: typeof ApiPublicStaffPinLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  CateringRoute: CateringRoute,
  CreditRoute: CreditRoute,
  DashboardRoute: DashboardRoute,
  DrawerRoute: DrawerRoute,
  FlagsRoute: FlagsRoute,
  IngredientsRoute: IngredientsRoute,
  PosRoute: PosRoute,
  PurchasesRoute: PurchasesRoute,
  RecipesRoute: RecipesRoute,
  StaffRoute: StaffRoute,
  SupplierPaymentRoute: SupplierPaymentRoute,
  WastageRoute: WastageRoute,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  ApiPublicCashDrawerCloseRoute: ApiPublicCashDrawerCloseRoute,
  ApiPublicStaffAdminRoute: ApiPublicStaffAdminRoute,
  ApiPublicStaffPinLoginRoute: ApiPublicStaffPinLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
